services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: crypto_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        ports:
            - "13579:80" # Expose the app frontend only on port 13579

networks:
    laravel:
        driver: bridge
