name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql, zip, gd
          tools: composer:v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Install NPM Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/your-app
            git pull origin main
            composer install --no-interaction --no-progress --prefer-dist
            npm install
            npm run build
            php artisan migrate --force
            php artisan config:cache
            php artisan queue:restart
            sudo systemctl restart php8.3-fpm
