name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql, zip, gd
          tools: composer:v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Install NPM Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Run Tests
        run: |
          php artisan key:generate --env=testing
          php artisan test --env=testing

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/your-app
            git pull origin main
            composer install --no-interaction --no-progress --prefer-dist
            
            # Rename .env.example to .env if it doesn't exist
            [ ! -f .env ] && mv .env.example .env

            chmod -R 775 storage bootstrap/cache

            npm install
            npm run build

            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache

            php artisan migrate --force

            php artisan queue:restart

            # Restart PHP-FPM safely
            sudo systemctl restart php8.3-fpm || sudo systemctl restart php-fpm

            # Reload Nginx (if needed)
            sudo systemctl reload nginx
